import Head from "next/head";
import Header from "./Header";

export default function Layout({ children, title = "Monoma" }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-screen-md mx-auto p-6">
        <Header />
        <div className="mt-2">{children}</div>
      </div>
    </>
  );
}
